# Generated by Django 5.2.8 on 2025-11-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='original_file_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
